MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/content/drive/ColabNotebooks/maskrcnn-benchmark/weights/trimmed_weights/trimmed_e2e_faster_rcnn_R_50_FPN_1x_ogconfig.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("aicity_2019_train", )
  TEST: ("aicity_2019_val", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  STEPS: (70000,)
  IMS_PER_BATCH: 1
  MAX_ITER: 90000
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "/content/drive/ColabNotebooks/maskrcnn-benchmark/results/AICITY_finetuning_FastRCNN/"
